version: '3'
services:
  postgres:
    image: postgis/postgis:16-master
    # Required when running on platform other than amd64, like Apple M1/M2:
    # platform: linux/amd64
    volumes:
      - ./.docker-data/database:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: medusa
      POSTGRES_PASSWORD: medusa

  redis:
    image: redis:7